version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27017:27017" # Mapeo del puerto para la conexión a MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: films
    volumes:
      - mongo_data:/data/db
      - ./data-mongo.js:/docker-entrypoint-initdb.d/data-mongo.js:ro
    restart: always

  web:
    build: ./flask-app
    container_name: webhost
    ports:
      - "5000:3000" # Puerto externo 5000 para la aplicación Flask
    environment:
      MONGO_URI: mongodb://mongodb:27017/films # URI de conexión a MongoDB
    depends_on:
      - mongodb # Garantiza que MongoDB se inicie antes del servidor Flask
    restart: always

volumes:
  mongo_data:
